# Generated by Django 5.1 on 2026-02-12 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 12, 4, 53, 6, 261890, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
